---
- name: Provision all in one vm
  hosts: all
  gather_facts: yes
  become: True
  roles:
    - kernel
    - base_pkgs
    - contrail
  vars:
    set_root_pass: 'contrail'
    instances_template: 'config_instances.j2'
    registry: 'bng-artifactory'
    contrail_deployer_branch: 'master'
    ntp_server: "ntp.juniper.net"
