---
- name: Provision all in one vm
  hosts: all
  gather_facts: yes
  become: True
  roles:
    - contrail
  vars:
    set_root_pass: 'contrail'
    instances_template: 'config_ha_instances.j2'
    registry: 'bng-artifactory'
