---
- hosts: all
  gather_facts: yes
  become: True
  tasks:
    - name: Upgrade kernel version for releases greater than 19O9
      yum:
        name: kernel
        state: latest

    - name: Upgrade kernel-devel version for releases greater than 19O9
      yum:
        name: kernel-devel
        state: latest
    
    - name: Reboot server
      reboot:
        reboot_timeout: 300

    - name: Check if server is up
      debug:
        msg: Server is up


 
