---
- name: Provision multinode instances
  hosts: all
  gather_facts: no
  become: True
  roles:
    - contrail
  vars:
    set_root_pass: 'contrail'
    instances_template: 'config_multinode_instances.j2'
    contrail_deployer_branch: 'master'
    registry: 'bng-artifactory'
