---
- name: Provision ui vm
  hosts: all
  gather_facts: yes
  become: True
  roles:
    - setup_root
    - command
  vars:
    set_root_pass: 'contrail'
    registry: 'bng-artifactory'
    vagrant_root: ""

