---
- name: Clone contrail-dev-env
  git:
    repo: https://github.com/tungstenfabric/tf-dev-env.git
    dest: /root/contrail-dev-env
    version: "master"

- name: Adding contrail-tpc repository
  blockinfile:
    path: /etc/yum.repos.d/tpc.repo
    create: yes
    block: |
      [contrail-tpc]
      name=Third parties for Contrail
      baseurl=http://tf-nexus.progmaticlab.com/repository/yum-tpc/
      enabled=1
      gpgcheck=0

#- name: initialize repo with branch in contrail-dev-env/vm-dev-env/init.sh
#  replace:
#    path: /root/contrail-dev-env/vm-dev-env/init.sh
#    regexp: "repo init --no-clone-bundle -q -u https://github.com/Juniper/contrail-vnc"
#    replace: "repo init --no-clone-bundle -q -u https://github.com/Juniper/contrail-vnc -b {{ branch }}"

#- name: comment out sudo yum -y update in contrail-dev-env/vm-dev-env/init.sh after cloning
#  replace:
#    path: /root/contrail-dev-env/vm-dev-env/init.sh
#    regexp: "sudo yum -y update"
#    replace: "# sudo yum -y update"

#- name: run startup.sh to install dev containers
#  shell: cd /root/contrail-dev-env && (./startup.sh -b || true) && ./vm-dev-env/init.sh

#- name: Get kernel version of vm
#  shell: uname -r | awk -F.x86_64 '{print $1}'
#  register: response

#- set_fact:
#    req_version: "{{ response.stdout }}"

#- debug:
#    msg: "{{ req_version }}"

#- name: Change kernel version in spec files
#  replace:
#    path: "{{ item.path }}"
#    regexp: 'BuildRequires: kernel = (.+)\.el7'
#   replace: "BuildRequires: kernel = {{ req_version }}"
#  with_items:
#    - {path: '/root/contrail/tools/packages/rpm/contrail/contrail.spec'}
#    - {path: '/root/contrail/tools/packages/rpm/contrail-vrouter-dpdk/contrail-vrouter-dpdk.spec'}

#- name: Change kernel-devel version in spec files
#  replace:
#    path: "{{ item.path }}"
#   regexp: 'BuildRequires: kernel-devel = (.+)\.el7'
#    replace: "BuildRequires: kernel-devel = {{ req_version }}"
#  with_items:
#    - {path: '/root/contrail/tools/packages/rpm/contrail/contrail.spec'}
#    - {path: '/root/contrail/tools/packages/rpm/contrail-vrouter-dpdk/contrail-vrouter-dpdk.spec'}

#- name: initialize dev env
#  shell: export LC_ALL=en_US.UTF-8 && export LANG=en_US.UTF-8 && export LANGUAGE=en_US.UTF-8 && export LC_TYPE=en_US.UTF-8 && cd /root/contrail && make -f tools/packages/Makefile dep && python3 third_party/fetch_packages.py

- name: Ensure env variables present in .bashrc
  blockinfile:
    path: /root/.bashrc
    block: |
      export GERRIT_BRANCH={{ branch }}
      export CONTRAIL_BRANCH={{ branch }}
      export CONTRAIL=/root/contrail
      export LC_ALL=en_US.UTF-8
      export LANG=en_US.UTF-8
      export LANGUAGE=en_US.UTF-8
      export LC_TYPE=en_US.UTF-8
      export LD_LIBRARY_PATH=$CONTRAIL/build/lib:$LD_LIBRARY_PATH

- name: Ensure createrepo is present
  yum:
    name: createrepo
    state: present

#- name: auto start docker.server at boot
#  systemd: name=docker enabled=yes

