---
- name: Install net-tools
  yum:
    name: net-tools
    state: latest

- name: Install wget
  yum:
    name: wget
    state: latest

- name: Install python-devel
  yum:
    name: python-devel
    state: latest

- name: Install python-pip
  yum:
    name: python-pip
    state: present

- name: Upgrade pip
  pip:
    name: pip==20.3.4
    state: present

- name: Install tree
  yum:
    name: tree
    state: latest

- name: Install vim
  yum:
    name: vim
    state: latest

- name: Install git review
  pip:
    name: git-review
    state: latest

- name: Install more-itertools 5.0.0 
  pip:
    name: more-itertools==5.0.0
    state: present

- name: Install tox
  pip:
    name: tox
    state: present

- name: Install gevent
  pip:
    name: gevent==1.4.0
    state: present

- name: Install geventhttpclient
  pip:
    name: geventhttpclient==1.3.1
    state: latest

- name: Install cscope 
  yum:
    name: cscope 
    state: latest

- name: Install bzip2-devel
  yum:
    name: bzip2-devel
    state: latest

- name: Install openssl
  yum:
    name: openssl-devel
    state: latest

- name: Install python36
  yum:
    name: python36
    state: present

- name: Install jq
  yum:
    name: jq
    state: present

- name: Install packages for vrouter
  yum:
    name:
      - numactl-devel
      - libpcap-devel
      - userspace-rcu
      - userspace-rcu-devel
      - libnl-devel
      - libnl
      - libnl3-devel
      - libxml2
      - libxml2-devel
      - libxml2-python
      - libxslt
      - libxslt-devel
    state: present

- name: Install future, lxml
  pip:
    name:
      - lxml
      - future
    state: present

- name: Install zip
  pip:
    name: zipp==0.5.2
    state: present

- name: Install configparser
  pip:
    name: configparser==4.0.2
    state: present

- name: Install virtualenv
  pip:
    name: virtualenv==16.1.0
    state: present

- name: ensure that 127.0.0.1 reverse resolves to only 'localhost'
  lineinfile:
    path: '/etc/hosts'
    line: '127.0.0.1 localhost'
    regexp: '^127\.0\.0\.1'
  become: true

- name: ensure that ::1 reverse resolves to only 'localhost'
  lineinfile:
    path: '/etc/hosts'
    line: '::1 localhost'
    regexp: '^::1'
  become: true

